name: my_flutter_gallery
description: Personal Site with Flutter Gallery Showcase
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gradient_animation_text: ^1.0.2
  flutter_layout_grid: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lowframer:
    path: shared/lowframer
  meta: ^1.11.0
  neubrutalism_ui: ^2.0.2
  package_info_plus: ^8.1.0
  shadcn_ui: ^0.8.1
  shared_utils:
    path: shared/shared_utils
  store_picker:
    path: packages/store_picker
  timelines: ^0.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
