name: my_flutter_gallery
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  intl: ^0.19.0
  meta: ^1.11.0
  neubrutalism_ui: ^2.0.2
  package_info_plus: ^7.0.0
  shadcn_ui: ^0.8.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
