name: cinema_store_pickers
description: Customizable product pickers for cinema store apps
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  lowframer:
    path: ../../shared/lowframer

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
