name: store_picker
description: Create product variant customization pickers for any store
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  device_preview: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  flutter_riverpod: ^2.0.0
  font_awesome_flutter: ^10.7.0
  hexcolor: ^3.0.1
  lowframer:
    path: ../../shared/lowframer
  money2: ^5.3.0
  shadcn_ui: ^0.15.1
  shared_utils:
    path: ../../shared/shared_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
