name: roadie
description: Transform any course content into interactive learning
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  shadcn_ui: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
